# c35784aef731b98729231fb4e9d3cc9372547cca encoding: utf-8
# @@ 1

########################### DO NOT MODIFY THIS FILE ###########################
#       This file was automatically generated by JRubyFX-fxmlloader on        #
# 2019-07-09 19:58:01 -0300 for /home/alatriste/programacion/sumario/data/inicio.fxml
########################### DO NOT MODIFY THIS FILE ###########################

module JRubyFX
  module GeneratedAssets
    class AOTef9ad8d136f6d07305eeb35f1bb164d236f3d2e9
      include JRubyFX
          def __build_via_jit(__local_fxml_controller, __local_namespace, __local_jruby_ext)
      __local_fx_id_setter = lambda do |name, __i|
        __local_namespace[name] = __i
        __local_fxml_controller.instance_variable_set(("@#{name}").to_sym, __i)
      end

build(Java::JavafxSceneLayout::AnchorPane) do
 __local_jruby_ext[:on_root_set].call(self) if __local_jruby_ext[:on_root_set]
 getChildren.add(build(Java::JavafxSceneControl::Button) do
  setId("boton_generar_pdf")
  __local_fx_id_setter.call("boton_generar_pdf", self)
  setLayoutX(92.0)
  setLayoutY(384.0)
  setMnemonicParsing(false)
  setPrefHeight(47.0)
  setPrefWidth(121.0)
  setStyle("-fx-background-color: #4d9b9b;")
  setText("Generar PDF")
  setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "generar_pdf"))
 end)
 getChildren.add(build(Java::JavafxSceneControl::TextField) do
  setId("campo_archivo_sumario")
  __local_fx_id_setter.call("campo_archivo_sumario", self)
  setEditable(false)
  setLayoutX(65.0)
  setLayoutY(179.0)
 end)
 getChildren.add(build(Java::JavafxSceneControl::Label) do
  setId("etiqueta_archivo_sumarios")
  __local_fx_id_setter.call("etiqueta_archivo_sumarios", self)
  setLayoutX(249.0)
  setLayoutY(175.0)
  setPrefHeight(34.0)
  setPrefWidth(355.0)
  setText("Archivo CSV")
  setTextAlignment(Java::javafx::scene::text::TextAlignment::CENTER)
 end)
 getChildren.add(build(Java::JavafxSceneControl::Label) do
  setId("etiqueta_archivo_personal")
  __local_fx_id_setter.call("etiqueta_archivo_personal", self)
  setLayoutX(248.0)
  setLayoutY(286.0)
  setPrefHeight(26.0)
  setPrefWidth(327.0)
  setText("Archivo CSV")
 end)
 getChildren.add(build(Java::JavafxSceneControl::Button) do
  setId("boton_salir")
  __local_fx_id_setter.call("boton_salir", self)
  setLayoutX(366.0)
  setLayoutY(384.0)
  setMnemonicParsing(false)
  setPrefHeight(47.0)
  setPrefWidth(121.0)
  setStyle("-fx-background-color: #4d9b9b;")
  setText("Salir")
  setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "salir"))
 end)
 getChildren.add(build(Java::JavafxSceneControl::Label) do
  setFont(build(FxmlBuilderBuilder, {"size"=>"36.0"}, Java::JavafxSceneText::Font) do
  end)
  setAlignment(Java::javafx::geometry::Pos::CENTER)
  setLayoutX(150.0)
  setLayoutY(-2.0)
  setPrefHeight(73.0)
  setPrefWidth(327.0)
  setText("DILIGENCIAS PFA")
 end)
 getChildren.add(build(Java::JavafxSceneControl::Button) do
  setId("boton_seleccionar_sumarios")
  __local_fx_id_setter.call("boton_seleccionar_sumarios", self)
  setLayoutX(52.0)
  setLayoutY(146.0)
  setMnemonicParsing(false)
  setPrefHeight(26.0)
  setPrefWidth(196.0)
  setStyle("-fx-background-color: #4d9b9b;")
  setText("Seleccionar SUMARIOS")
  setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "seleccionar_sumarios"))
 end)
 getChildren.add(build(Java::JavafxSceneControl::Button) do
  setId("boton_seleccionar_personal")
  __local_fx_id_setter.call("boton_seleccionar_personal", self)
  setLayoutX(54.0)
  setLayoutY(258.0)
  setMnemonicParsing(false)
  setPrefHeight(26.0)
  setPrefWidth(196.0)
  setStyle("-fx-background-color: #4d9b9b;")
  setText("Seleccionar PERSONAL")
  setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "seleccionar_personal"))
 end)
 getChildren.add(build(Java::JavafxSceneControl::TextField) do
  setId("campo_archivo_personal")
  __local_fx_id_setter.call("campo_archivo_personal", self)
  setEditable(false)
  setLayoutX(65.0)
  setLayoutY(286.0)
 end)
 setMaxHeight(-Infinity)
 setMaxWidth(-Infinity)
 setMinHeight(-Infinity)
 setMinWidth(-Infinity)
 setPrefHeight(558.0)
 setPrefWidth(600.0)
 setStyle("-fx-background-color: #2f4f4f; -fx-border-color: #32465c;")
end
    end

      def hash
        "c35784aef731b98729231fb4e9d3cc9372547cca"
      end
      def compiled?
        true
      end
    end
  end
end
