# c6acd4d0105fbfe668275507c4ee616b65bc7fe8 encoding: utf-8
# @@ 1

########################### DO NOT MODIFY THIS FILE ###########################
#       This file was automatically generated by JRubyFX-fxmlloader on        #
# 2017-04-22 17:16:15 -0300 for /home/bayot/programacion/ruby/Memos/lib/memos.fxml
########################### DO NOT MODIFY THIS FILE ###########################

module JRubyFX
  module GeneratedAssets
    class AOT4225ffc71f6d4a3fc19dfd18277fcb02d3f529cd
      include JRubyFX
          def __build_via_jit(__local_fxml_controller, __local_namespace, __local_jruby_ext)
      __local_fx_id_setter = lambda do |name, __i|
        __local_namespace[name] = __i
        __local_fxml_controller.instance_variable_set(("@#{name}").to_sym, __i)
      end

build(Java::JavafxSceneLayout::AnchorPane) do
 __local_jruby_ext[:on_root_set].call(self) if __local_jruby_ext[:on_root_set]
 getChildren.add(build(Java::JavafxSceneControl::Button) do
  setId("boton_generar_pdf")
  __local_fx_id_setter.call("boton_generar_pdf", self)
  setLayoutX(83.0)
  setLayoutY(295.0)
  setMnemonicParsing(false)
  setPrefHeight(62.0)
  setPrefWidth(137.0)
  setText("Generar PDF")
  setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "generar_pdf"))
 end)
 getChildren.add(build(Java::JavafxSceneControl::DatePicker) do
  setId("seleccion_fecha")
  __local_fx_id_setter.call("seleccion_fecha", self)
  setEditable(false)
  setLayoutX(64.0)
  setLayoutY(138.0)
  setPrefHeight(26.0)
  setPrefWidth(171.0)
 end)
 getChildren.add(build(Java::JavafxSceneControl::TextField) do
  setId("campo_archivo_csv")
  __local_fx_id_setter.call("campo_archivo_csv", self)
  setEditable(false)
  setLayoutX(64.0)
  setLayoutY(97.0)
 end)
 getChildren.add(build(Java::JavafxSceneControl::Label) do
  setId("etiqueta_archivo_csv")
  __local_fx_id_setter.call("etiqueta_archivo_csv", self)
  setLayoutX(245.0)
  setLayoutY(97.0)
  setPrefHeight(34.0)
  setPrefWidth(355.0)
  setText("Archivo CSV")
  setTextAlignment(Java::javafx::scene::text::TextAlignment::CENTER)
 end)
 getChildren.add(build(Java::JavafxSceneControl::Label) do
  setId("etiqueta_fecha")
  __local_fx_id_setter.call("etiqueta_fecha", self)
  setLayoutX(245.0)
  setLayoutY(138.0)
  setPrefHeight(26.0)
  setPrefWidth(327.0)
  setText("Fecha de inasistencias")
 end)
 getChildren.add(build(Java::JavafxSceneControl::Button) do
  setId("boton_salir")
  __local_fx_id_setter.call("boton_salir", self)
  setLayoutX(354.0)
  setLayoutY(295.0)
  setMnemonicParsing(false)
  setPrefHeight(62.0)
  setPrefWidth(137.0)
  setText("Salir")
  setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "salir"))
 end)
 getChildren.add(build(Java::JavafxSceneControl::Label) do
  setFont(build(FxmlBuilderBuilder, {"size"=>"36.0"}, Java::JavafxSceneText::Font) do
  end)
  setAlignment(Java::javafx::geometry::Pos::CENTER)
  setLayoutX(150.0)
  setLayoutY(-2.0)
  setPrefHeight(73.0)
  setPrefWidth(291.0)
  setText("MEMOS PFA")
 end)
 getChildren.add(build(Java::JavafxSceneControl::Label) do
  setId("etiqueta_resultado")
  __local_fx_id_setter.call("etiqueta_resultado", self)
  setFont(build(FxmlBuilderBuilder, {"size"=>"11.0"}, Java::JavafxSceneText::Font) do
  end)
  setLayoutX(19.0)
  setLayoutY(245.0)
  setPrefHeight(26.0)
  setPrefWidth(562.0)
 end)
 getChildren.add(build(Java::JavafxSceneControl::Button) do
  setId("boton_seleccionar_csv")
  __local_fx_id_setter.call("boton_seleccionar_csv", self)
  setLayoutX(52.0)
  setLayoutY(58.0)
  setMnemonicParsing(false)
  setPrefHeight(26.0)
  setPrefWidth(196.0)
  setText("Seleccionar Archivo CSV")
  setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "seleccionar_csv"))
 end)
 getChildren.add(build(Java::JavafxSceneControl::Button) do
  setId("boton_seleccionar_destino")
  __local_fx_id_setter.call("boton_seleccionar_destino", self)
  setLayoutX(53.0)
  setLayoutY(174.0)
  setMnemonicParsing(false)
  setPrefHeight(26.0)
  setPrefWidth(196.0)
  setText("Seleccionar Destino")
  setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "seleccionar_destino"))
 end)
 getChildren.add(build(Java::JavafxSceneControl::TextField) do
  setId("campo_directorio_destino")
  __local_fx_id_setter.call("campo_directorio_destino", self)
  setEditable(false)
  setLayoutX(66.0)
  setLayoutY(209.0)
 end)
 setMaxHeight(-Infinity)
 setMaxWidth(-Infinity)
 setMinHeight(-Infinity)
 setMinWidth(-Infinity)
 setPrefHeight(400.0)
 setPrefWidth(600.0)
end
    end

      def hash
        "c6acd4d0105fbfe668275507c4ee616b65bc7fe8"
      end
      def compiled?
        true
      end
    end
  end
end
